version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: worldofsports
    volumes:
      - .:/worldofsports
    ports:
      - "8000:8000"

# python manage.py makemigrations && python manage.py migrate && add in command