version: '3'

services:
  web:
    build: .
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 demo.wsgi:application"
    container_name: worldofsports
    volumes:
      - .:/worldofsports
    ports:
      - "8000:8000"

# python manage.py makemigrations && python manage.py migrate && add in command